### ISSUE TITLE
Erro no tipo de ISSN no XML enviado para registro do DOI

### ISSUE THREAD

**Issue by javani** [scieloorg/doi_request#4]
Está ocorrendo um erro de coleta de dado do ISSN de uma revista (não sei se em outros casos também) o que talvez esteja afetando o registro do dado no Lattes.
Exemplo:

O artigo PID http://articlemeta.scielo.org/api/v1/article/?code=S0006-87052017000400470 tem ambos os ISSNs (eletrônico e impresso)

![image 1](https://user-images.githubusercontent.com/912953/34221691-1e00be18-e5a0-11e7-9450-373414ce18f7.png)

Quando olhamos o depósito no crossref, verificamos que o ISSN impresso foi registrado como eletrônico.
![image 2](https://user-images.githubusercontent.com/912953/34221699-299a415e-e5a0-11e7-8dfe-581947d3e36f.png)

Há como verificar ou nos dizer onde está o problema? O natural não seria enviar ambos os ISSNs cada um com seu tipo específico?

**Comment by fabiobatalha** [comment]
Esta sendo corrigino no ArticleMeta o XML de exportação para o Crossref.

**Comment by fabiobatalha** [comment]
Solucionado
http://articlemeta.scielo.org/api/v1/article/?code=S0006-87052017000400470&format=xmlcrossref
